version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=$ecr_uri
      - echo REPOSITORY_URI=$REPOSITORY_URI

      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker -v
      - docker login -u $dockerhub_username -p $dockerhub_password

      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
